the models
utopia-airlines/UtopiaAirlinesCounterAPI pull request #1
Opened 2019-06-24 20:53 UTC by al-amine

all the Models

2019-06-24 23:02 UTC, kingjon3377 requested changes
1. When I saw the title "the models" I expected to be reviewing only model code; because you developed on and made your pull request from the `master` branch this is a PR that includes everything so far. In projects where you are not the sole developer, do not work directly on the master branch!

2. Most of my comments about @STOzaki's utopia-airlines/UtopiaAirlinesAgentAPI#2 also apply here. Most seriously, the controller methods you have created expose a REST API that is quite different from what we agreed on, documented, and presented to the product owners. That needs to change before they can be merged.

2019-06-24 23:02 UTC, kingjon3377 commented on src/main/java/com/st/utopia/counter/CounterAppApplication.java
> +	public RestTemplate getRestTemnplate() {
You've misspelled "Template" in the name of the method.

2019-06-24 23:02 UTC, kingjon3377 commented on src/main/java/com/st/utopia/counter/contoller/CounterBookingController.java
> +	@Value("${utopia.booking-service-hostName}")
As I mentioned in my review of @STOzaki's utopia-airlines/UtopiaAirlinesAgentAPI#2, please use a consistent naming convention for properties.

2019-06-24 23:02 UTC, kingjon3377 commented on src/main/java/com/st/utopia/counter/contoller/CounterBookingController.java
> +	private String hostName;
Also as I mentioned in my review of @STOzaki's utopia-airlines/UtopiaAirlinesAgentAPI#2, I think it would be much better to inject a single "endpoint" property instead of hostname, port, and prefix separately.

2019-06-24 23:02 UTC, kingjon3377 commented on src/main/java/com/st/utopia/counter/contoller/CounterBookingController.java
> +	@PostMapping("/book/flights/{flight}/rows/{row}/seats/{seat}")
Also as I mentioned in my review of @STOzaki's utopia-airlines/UtopiaAirlinesAgentAPI#2, this is not the API we agreed on and documented in the Swagger specification.

2019-06-24 23:02 UTC, kingjon3377 commented on src/main/java/com/st/utopia/counter/contoller/CounterBookingController.java
> +	public ResponseEntity<Ticket> getAllBranchCopies(@PathVariable final int flight, @PathVariable final int row,
`getAllBranchCopies`?

2019-06-24 23:02 UTC, kingjon3377 commented on src/main/java/com/st/utopia/counter/contoller/CounterCancellationController.java
> +@CrossOrigin
You have `@CrossOrigin` on this but not on the "booking" controller. Which is right?

2019-06-24 23:02 UTC, kingjon3377 commented on src/main/java/com/st/utopia/counter/contoller/CounterSearchController.java
> +	@SuppressWarnings("rawtypes")
One of the main points of the `ParameterizedTypeReference` subclass in the `methodCall` method is to allow us to specify full type parameters; if you have a "raw types" warning, in the *vast* majority of cases you should fix it. (If nothing else, a raw `List` can be changed to a `List<Object>`.)

2019-06-24 23:02 UTC, kingjon3377 commented on src/main/java/com/st/utopia/counter/entity/Airport.java
> + * provided, but to support JPA providers fields are not made final.
You won't be doing JPA in this service, so you can remove references to it from the documentation (and you can make the fields `final` if you like).

2019-06-24 23:02 UTC, kingjon3377 commented on src/main/java/com/st/utopia/counter/entity/Airport.java
> +	 * Non-default constructor, provided for tests.
I don't see any tests, so I doubt you need the full-featured constructors. (Which means the no-argument constructor can be removed too, as it's generated by default if no constructors are explicitly defined.)

2019-06-24 23:02 UTC, kingjon3377 commented on src/main/java/com/st/utopia/counter/entity/Ticket.java
> + * microservice will search for the ticket via booking_id which is unique
The user-facing API allows tickets to be cancelled *either* by their flight number, row, and seat *or* by their booking ID.

2019-06-24 23:02 UTC, kingjon3377 commented on src/main/java/com/st/utopia/counter/entity/Ticket.java
> + * Upon cancelling the ticket, the microservice needs to set the following
Upon cancelling the ticket, surely the backend service should return the new data for the ticket, and that should be what is returned to the caller? (In which case, I suggest removing this paragraph.)

2019-06-24 23:02 UTC, kingjon3377 commented on src/main/java/com/st/utopia/counter/entity/Ticket.java
> +	private Integer tier; // class is a keyword
Use an annotation to make Jackson see this field as corresponding to a `class` field in JSON objects.

2019-06-24 23:02 UTC, kingjon3377 commented on src/main/java/com/st/utopia/counter/entity/TicketIdentity.java
> + * Declared to implement Serializable because "Composite-id class must implement
Because there's no JPA in this user-facing microservice, you can remove all `Serializable` boilerplate.

2019-06-24 23:02 UTC, kingjon3377 commented on src/main/resources/application.properties
> +management.endpoints.web.exposure.include=beans
What does this do?

2019-06-24 23:02 UTC, kingjon3377 commented on src/main/resources/application.properties
> +server.port=8081
As Akbar said, this is a "code smell": for local testing purposes you can override the default on the command line, but for Docker-based deployment it should be left to the default.

2019-06-26 19:57 UTC, kingjon3377 requested changes
There are a few places where the API deviates slightly from what we've documented in the Swagger specification, and a couple of routes that the specification does not include.

2019-06-26 19:57 UTC, kingjon3377 commented on src/main/java/com/st/utopia/counter/controller/CounterBookingController.java
> +	public ResponseEntity<TicketIdentity> getAllSeatsWithPlan(
`getAllSeatsWithPlan` doesn't convey what this method does: what "plan"?

2019-06-26 19:57 UTC, kingjon3377 commented on src/main/java/com/st/utopia/counter/controller/CounterBookingController.java
> +	 * @return a ticket
Your `@return` documentation of most of these methods' return values amounts to nothing more than we can already see from the return *type*; this should say what the return *value* is. (This is the ticket corresponding to the given seat on the given flight; `updateTicket` returns the updated details of the ticket, etc.)

2019-06-26 19:57 UTC, kingjon3377 commented on src/main/java/com/st/utopia/counter/controller/CounterSearchController.java
> +	@GetMapping("/airports/{code}")
In the API we've documented this should be `/airport/{code}`.

2019-06-26 19:57 UTC, kingjon3377 commented on src/main/java/com/st/utopia/counter/controller/CounterSearchController.java
> +	@GetMapping("/flights/{flightId}")
In the API we've documented this should be `/flight/{flightId}`.

2019-06-26 19:57 UTC, kingjon3377 commented on src/main/java/com/st/utopia/counter/controller/CounterBookingController.java
> +	@GetMapping("/flight/{flightId}/seat/{row}/{seatId}")
This same information needs to also be returned for `/flight/{flightId}/seat/{row}/{seatId}/ticket`.

2019-06-26 19:57 UTC, kingjon3377 commented on src/main/java/com/st/utopia/counter/controller/CounterCancellationController.java
> +public class CounterCancellationController {
The routes in this file are not part of the API we documented, and seem to duplicate functionality you provide elsewhere.

2019-06-26 22:04 UTC, kingjon3377 approved these changes
In future, please make your commit messages more descriptive, but the code changes are acceptable at this point.

2019-06-26 23:35 UTC, STOzaki approved these changes
looks good, and thank you for testing it

2019-06-27 05:17 UTC, merged